import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <a
          href="https://github.com/login/oauth/authorize?client_id=b5bd86ba39b6f7e84d16"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>connect</p>
        </a>
      </main>
    </>
  );
}
